# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - ./deployment.yaml

namespace: default
commonLabels:
  app: mini-api
  env: dev

images:
  - name: mini-api # match images with this name
    newTag: sha-901df06c # override the tag
    newName: ghcr.io/alphawong/mini-api # override the name

configMapGenerator:
  - name: dev.env
    env: dev.env
secretGenerator:
  - name: dev.key
    env: dev-key.env

vars:
  - name: APP_PORT
    objref:
      kind: ConfigMap
      name: dev.env
      apiVersion: v1
    fieldref:
      fieldpath: data.FLASK_PORT

configurations:
  - kustomizeconfig.yaml
