apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mini-api-service
  name: mini-api-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: $(APP_PORT)
      nodePort: 8080
  selector:
    name: $(BACKEND_APP_NAME)
  type: NodePort
status:
  loadBalancer: {}
