apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mini-api-service
  name: mini-api-service
spec:
  ports:
    - port: 8080
  selector:
    app: mini-api
    component: python
    env: dev
    tier: backend
  type: LoadBalancer
status:
  loadBalancer: {}
